add cloud credentials type + routes
armosec/config-service pull request #139
Opened 2024-07-16 11:26 UTC by idohuber

add new data type name cloud_credentials and added matching route

2024-07-16 11:41 UTC, Bezbran requested changes
Where are the unitests????

2024-07-16 11:41 UTC, Bezbran commented on routes/v1/cloud_credentials/routes.go
> +		WithValidatePostUniqueName(true).
Do we need to enforce this uniqueness?
It means customers are unable to create 2 creds with the same name

2024-07-16 11:41 UTC, Bezbran commented on types/cloud_credentials.go
> +	EncryptedExternalKey string       `json:"encryptedExternalKey" bson:"encryptedExternalKey"`
We are missing here all the "omitempty" stuff

2024-07-16 12:55 UTC, idohuber commented on types/cloud_credentials.go
> +	EncryptedExternalKey string       `json:"encryptedExternalKey" bson:"encryptedExternalKey"`
if you remember we puted it in Crdentials and omitempty all the full struct

2024-07-16 12:57 UTC, idohuber commented on types/cloud_credentials.go
> +	EncryptedExternalKey string       `json:"encryptedExternalKey" bson:"encryptedExternalKey"`
type Credentials struct {
	AwsCredentials   `json:",inline" bson:"awsCredentials,omitempty"`
	AzureCredentials `json:",inline" bson:"azureCredentials,omitempty"`
}

2024-07-16 13:00 UTC, idohuber commented on routes/v1/cloud_credentials/routes.go
> +		WithValidatePostUniqueName(true).
we only need unique names only in the same provider ,
between providers it doesnt matter (maybe it will have effect on the ui?)
becuse we will filter accound by guid not by name

2024-07-16 13:07 UTC, Bezbran commented on routes/v1/cloud_credentials/routes.go
> +		WithValidatePostUniqueName(true).
So is it by purpose or not?

2024-07-16 13:09 UTC, Bezbran commented on types/cloud_credentials.go
> +	EncryptedExternalKey string       `json:"encryptedExternalKey" bson:"encryptedExternalKey"`
AFAIK we should put them on each field, since it's composite struct

2024-07-16 13:41 UTC, idohuber commented on routes/v1/cloud_credentials/routes.go
> +		WithValidatePostUniqueName(true).
not ,
i am asking a further question - if what i am saying is logical

2024-07-16 13:43 UTC, idohuber commented on types/cloud_credentials.go
> +	EncryptedExternalKey string       `json:"encryptedExternalKey" bson:"encryptedExternalKey"`
kk will add

2024-08-20 08:49 UTC, jnathangreeg approved these changes

2024-08-21 08:37 UTC, amirmalka commented on routes/v1/cloud_credentials/routes.go
> +	//IDO: understnd how do not update the name if it is empty
Is it a TODO?

2024-08-21 08:38 UTC, amirmalka commented on routes/v1/cloud_credentials/routes.go
> +			fmt.Println(docs[i], docs[i].Enabled)
Is this print really necessary here?

2024-08-21 08:38 UTC, amirmalka commented on service_test.go
> +	// IDO: take out Regions and Services from the comparison , supposed to be ok
?

2024-08-21 08:38 UTC, amirmalka commented on service_test.go
> +	// IDO: take out Regions and Services from the comparison , supposed to be ok
Same here

2024-08-21 08:39 UTC, amirmalka reviewed
small things

2024-08-25 14:47 UTC, idohuber commented on routes/v1/cloud_credentials/routes.go
> +	//IDO: understnd how do not update the name if it is empty
yes its IDO , i made custom, TODO for myself

2024-08-25 14:48 UTC, idohuber commented on routes/v1/cloud_credentials/routes.go
> +	//IDO: understnd how do not update the name if it is empty
solved it

2024-08-26 11:06 UTC, amirmalka approved these changes

2024-08-26 11:09 UTC, merged